language: python

sudo: false

python:
  - "3.6"

services:
  - mysql
  - redis-server

before_install:
  - mysql -e 'CREATE DATABASE spider CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'

install:
  - make

script:
  - make test

after_success:
  - env/bin/codecov